server:
  port: 8761


eureka:
  instance:
    hostname: localhost
  client:
    #声明自己是个服务器
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: htpp://${eureka.instance.hostname}:${server.port}/eureka/
