server:
  port: 8781
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 127.0.0.1
#    password: 123456
    port: 6379
    timeout: 2000ms

#自定义负载均衡策略
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#设置连接时间和调用超时时间
feign:
  #2.0.3的fegin默认是关闭hystrix
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 1000
#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
#设置hystrix超时时间
hystrix:
  command:
    myusers-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

