#服务名称
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hch-lone-wolf/config-server
          username:
          password:
          timeout: 5
          default-label: master
#端口
server:
  port: 9100

#指定注册中心地址
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
