server:
  port: 9000
spring:
  application:
    name: api-gateway
#指定注册中心地址
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
#名称如果一样会覆盖前者
zuul:
  routes:
    order-service: /apigateway/order/**
    product-service: /apigateway/product/**
 #处理请求头为空的问题
  sensitive-headers:
 #统一入口为上面的配置，其他入口忽略
 #ignored-patterns: /*-service/**
 #忽略整个服务，对外提供接口
 #ignored-services: product-service